export const homesArray = [
  {
    "imageInfo": {
      "id": 36711202,
      "isLiked": false,
      "bookmarkDataId": 0,
      "title": "Nottingham Vintage by Keystone Custom Homes | Available at Forest Knoll in Baltimore",
      "path": "https://nhs-dynamic.secure.footprint.net/Images/Homes/KeystoneCustomHomes/36243649-190712.jpg",
      "caption": "4 Bd | 2 Ba | 3,602 sq. ft. | This luxurious living space by Keystone Custom Homes is waiting for your personal touch!",
      "description": "See inspiring photos - room-by-room - from top home builders near you at HomLuv.com.",
      "altTag": "Living Area featured in the Nottingham Vintage By Keystone Custom Homes in Baltimore",
      "type": "INT",
      "masonClass": null,
    },
    "homeInfo": {
      "bookmarkDataId": 43203,
      "isSaved": true,
      "status": "R",
      "statusDescription": "Ready To Build",
      "zip": "21050",
      "homeId": 1395475,
      "listingId": 67616696,
      "planName": "Nottingham Vintage",
      "isSpec": false,
      "marketId": 142,
      "marketName": "Baltimore",
      "builderId": 9459,
      "price": 516620,
      "thumb": "https://nhs-dynamic.secure.footprint.net/Images/Homes/KeystoneCustomHomes/36642948-190728.jpg",
      "phone": "888-375-3816",
      "bed": 4,
      "bath": 2,
      "square": 3602,
      "brand": {
        "id": 3465,
        "name": "Keystone Custom Homes",
        "logo": "https://nhs-dynamic.secure.footprint.net/images/brands/3465-MED.jpg",
        "logoSmall": "https://nhs-dynamic.secure.footprint.net/images/brands/3465-SML.jpg",
        "siteUrl": "www.keystonecustomhome.com",
      },
      "commName": "Forest Knoll",
      "builderName": "Keystone Custom Homes",
      "state": "MD",
      "address": "2311 Issac's Way",
      "city": "Forest Hill",
      "imageCount": 0,
    },
    "lat": 39.581211,
    "long": -76.385299,
    "address": "2311 Issac's Way",
    "fitBounds": true
  },
  {
    "imageInfo": {
      "id": 34138934,
      "isLiked": false,
      "bookmarkDataId": 0,
      "title": "Granada I by Homes by WestBay | Available at Pristine Lake Preserve in Tampa-St. Petersburg",
      "path": "https://nhs-dynamic.secure.footprint.net/Images/Homes/Homes11401/34137792-190506.jpg",
      "caption": "7 Bd | 5 Ba | 4,828 sq. ft. | Make the Granada I floorplan the first step on the way to your new dream home!",
      "description": "See inspiring images of new homes near you at HomLuv.com.",
      "altTag": "Exterior featured in the Granada I By Homes by WestBay in Tampa-St. Petersburg",
      "type": "INT",
      "masonClass": null,
    },
    "homeInfo": {
      "bookmarkDataId": 43204,
      "isSaved": true,
      "status": "R",
      "statusDescription": "Ready To Build",
      "zip": "34639",
      "homeId": 1644155,
      "listingId": 68241639,
      "planName": "Granada I",
      "isSpec": false,
      "marketId": 80,
      "marketName": "Tampa-St. Petersburg",
      "builderId": 11402,
      "price": 474990,
      "thumb": "https://nhs-dynamic.secure.footprint.net/Images/Homes/Homes11401/34137767-190506.jpg",
      "phone": "888-237-8113",
      "bed": 7,
      "bath": 5,
      "square": 4828,
      "brand": {
        "id": 1746,
        "name": "Homes by WestBay",
        "logo": "https://nhs-dynamic.secure.footprint.net/images/brands/1746-MED.jpg",
        "logoSmall": "https://nhs-dynamic.secure.footprint.net/images/brands/1746-SML.jpg",
        "siteUrl": "www.tampabayparadeofhomes.com",
      },
      "commName": "Pristine Lake Preserve",
      "builderName": "Homes by WestBay",
      "state": "FL",
      "address": "21758 Pristine Lake Blvd",
      "city": "Land O Lakes",
      "imageCount": 0
    },
    "lat": 28.25189,
    "long": -82.450373,
    "address": "21758 Pristine Lake Blvd",
    "fitBounds": true

  },
  {
    "imageInfo": {
      "id": 29584014,
      "isLiked": false,
      "bookmarkDataId": 0,
      "title": "The Whidbey - Build On Your Land by Adair Homes | Available at Mid Columbia Valley in Richland",
      "path": "https://nhs-dynamic.secure.footprint.net/Images/Homes/Adair18093/29580358-180919.jpg",
      "caption": "3 Bd | 2 Ba | 1,634 sq. ft. | Live in style with this trendy Living Room design available in the Richland area!",
      "description": "See inspiring images of new homes near you at HomLuv.com.",
      "altTag": "Living Area featured in The Whidbey - Build On Your Land By Adair Homes in Richland",
      "type": "INT",
      "masonClass": null,
    },
    "homeInfo": {
      "bookmarkDataId": 43763,
      "isSaved": true,
      "status": "R",
      "statusDescription": "Ready To Build",
      "zip": "99336",
      "homeId": 1551934,
      "listingId": 68036955,
      "planName": "The Whidbey - Build On Your Land",
      "isSpec": false,
      "marketId": 307,
      "marketName": "Richland",
      "builderId": 18125,
      "price": 146999,
      "thumb": "https://nhs-dynamic.secure.footprint.net/Images/Homes/Adair18093/29580348-180919.jpg",
      "phone": "888-768-1002",
      "bed": 3,
      "bath": 2,
      "square": 1634,
      "brand": {
        "id": 8277,
        "name": "Adair Homes",
        "logo": "https://nhs-dynamic.secure.footprint.net/images/brands/8277-MED.jpg",
        "logoSmall": "https://nhs-dynamic.secure.footprint.net/images/brands/8277-SML.jpg",
        "siteUrl": "www.adairhomes.com"
      },
      "commName": "Mid Columbia Valley",
      "builderName": "Adair Homes",
      "state": "WA",
      "address": "1915 Steptoe St Suite C",
      "city": "Kennewick",
      "imageCount": 0
    },
    "lat": 46.228244,
    "long": -119.244571,
    "address": "1915 Steptoe St Suite C",
    "fitBounds": true

  },
  {
    "imageInfo": {
      "id": 31946627,
      "isLiked": false,
      "bookmarkDataId": 0,
      "title": "Chopin ABC by William Lyon Homes | Available at Maya Vista in Austin",
      "path": "https://nhs-dynamic.secure.footprint.net/Images/Homes/AHVHo18396/31932466-190124.jpg",
      "caption": "3 Bd | 2 Ba | 1,692 sq. ft. | Make your new home an adventure with the flexible Chopin ABC floorplan from William Lyon Homes!",
      "description": "See inspiring images of new homes near you at HomLuv.com.",
      "altTag": "Exterior featured in the Chopin ABC By William Lyon Homes in Austin",
      "type": "ELE",
      "masonClass": null,
    },
    "homeInfo": {
      "bookmarkDataId": 43764,
      "isSaved": true,
      "status": "R",
      "statusDescription": "Ready To Build",
      "zip": "78641",
      "homeId": 1597889,
      "listingId": 68141969,
      "planName": "Chopin ABC",
      "isSpec": false,
      "marketId": 269,
      "marketName": "Austin",
      "builderId": 44858,
      "price": 252990,
      "thumb": "https://nhs-dynamic.secure.footprint.net/Images/Homes/AHVHo18396/31932464-190124.jpg",
      "phone": "888-898-4871",
      "bed": 3,
      "bath": 2,
      "square": 1692,
      "brand": {
        "id": 2094,
        "name": "William Lyon Homes",
        "logo": "https://nhs-dynamic.secure.footprint.net/images/brands/3688438_MED.gif",
        "logoSmall": "https://nhs-dynamic.secure.footprint.net/images/brands/3688439_SML.gif",
        "siteUrl": "LyonColorado.com",
      },
      "commName": "Maya Vista",
      "builderName": "RSI Communities Central TX",
      "state": "TX",
      "address": "329 Akumal Avenue",
      "city": "Leander",
      "imageCount": 0,
    },
    "lat": 30.593676,
    "long": -97.863555,
    "address": "329 Akumal Avenue",
    "fitBounds": true

  }
]